name = "Expokit"
uuid = "3d6060e2-590d-4175-9f25-78299e29e9b8"
authors = ["Alexander Croy", "Jonathan Doucette <jdoucette@phas.ubc.ca>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.0"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays"]
